frase = "   Curso em Video Python.  "
print(len(frase))
print(frase.count("o",0,13))
print(frase.find("deo"))
print("CURSO" in frase)
print(frase.replace("PYTHON", "ANDROID"))
print(frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
frase01 = frase.split()
print(frase.split(maxsplit=1))
print("-".join(frase01))