frase = "   Curso em Video Python.  "
print(len(frase))
print(frase.count("o",0,13))
print(frase.find("deo"))
print("CURSO" in frase)
print(frase.replace("PYTHON", "ANDROID"))
print(frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
frase01 = frase.split()
print(frase.split(maxsplit=1))
print("-".join(frase01))

print("""Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since 1966, when designers at Letraset and James Mosley, the librarian at St Bride Printing Library, took a 1914 Cicero translation and scrambled it to make dummy text for Letraset's Body Type sheets. It has survived not only many decades, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised thanks to these sheets and more recently with desktop publishing software including versions of Lorem Ipsum.""")